---
- name: Create test user account
  user:
    name: test
    comment: test
    password: $6$xSlfvkcsDgPmRAMX$mFh9qRmFFW9cyW1n5/jeHvq4OmJA8WzSD70Mfis3VHc3Z5imZeiQAg9VNL4sFEtmDy/siU3nJL.QeAapCgfL20
    shell: '{{ bash }}'

- name: Configure ssh access for the test user
  authorized_key:
    user: test
    key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/id_rsa.pub") }}'
    state: present

- name: Grant passwordless sudo access to the test user
  lineinfile:
    path: '{{ sudoers }}'
    line: 'test ALL=(ALL) NOPASSWD: ALL'
    state: present
    backup: yes
    validate: 'visudo -cf %s'
